import { FishItem, MarketplaceItem, BuyerProfile, NotificationItem, ProfitRecord, FarmGuideStep, FishGrade, UserListing } from "./types";

export const REF_DATES = {
  today: "2026-06-12",
  yesterday: "2026-06-11",
};

export const MOCK_FISH_SPECIES: FishItem[] = [
  {
    id: "tilapia",
    name: "Red Tilapia",
    malayName: "Tilapia Merah",
    scientificName: "Oreochromis sp.",
    image: "https://images.unsplash.com/photo-1534080391025-a77af6eb21a7?auto=format&fit=crop&q=80&w=600", // Generic underwater/fish image
    farmPrice: 6.5,
    marketPrice: 9.0,
    category: "Freshwater",
    description: "Highly resilient freshwater fish, perfect for beginners in backyard biofloc farming. Fast growth and strong local demand.",
    difficulty: "Easy",
    growthCycleWeeks: 24,
  },
  {
    id: "catfish",
    name: "African Catfish",
    malayName: "Ikan Keli",
    scientificName: "Clarias gariepinus",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=600",
    farmPrice: 5.0,
    marketPrice: 7.5,
    category: "Freshwater",
    description: "Extremely hardy, thrives in ultra-dense water conditions. Has a very high survival rate and matures extremely quickly.",
    difficulty: "Easy",
    growthCycleWeeks: 16,
  },
  {
    id: "seabass",
    name: "Barramundi / Sea Bass",
    malayName: "Ikan Siakap",
    scientificName: "Lates calcarifer",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=600",
    farmPrice: 12.0,
    marketPrice: 17.5,
    category: "Brackish",
    description: "Highly sought-after premium fish in restaurants. Requires careful salinity management but yields excellent profit margins.",
    difficulty: "Hard",
    growthCycleWeeks: 32,
  },
  {
    id: "snapper",
    name: "Red Snapper",
    malayName: "Ikan Merah",
    scientificName: "Lutjanus campechanus",
    image: "https://images.unsplash.com/photo-1611171711810-bd896b55a475?auto=format&fit=crop&q=80&w=600",
    farmPrice: 16.0,
    marketPrice: 24.0,
    category: "Saltwater",
    description: "Premium marine species requiring high water quality, aeration and salinity levels. Yields the highest market trade value.",
    difficulty: "Hard",
    growthCycleWeeks: 36,
  }
];

export const MOCK_MARKETPLACE_LISTINGS: MarketplaceItem[] = [
  {
    id: "m1",
    fishId: "tilapia",
    fishName: "Red Tilapia Grade A",
    fishMalayName: "Tilapia Merah Gred A",
    farmName: "Lestari Aquaculture",
    farmerName: "Encik Ahmad Razak",
    location: "Kuala Terengganu, Terengganu",
    pricePerKg: 6.5,
    availableKg: 250,
    grade: FishGrade.A,
    isHalal: true,
    image: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    description: "Grown using high-quality pellet feed in biofloc tanks. Super clean, sweet meat, no muddy smell whatsoever. Live catch upon pickup.",
    dateListed: "2026-06-11",
  },
  {
    id: "m2",
    fishId: "catfish",
    fishName: "Fresh African Catfish",
    fishMalayName: "Ikan Keli Segar",
    farmName: "B40 Jaya Agro",
    farmerName: "Puan Fatimah Awang",
    location: "Sungai Petani, Kedah",
    pricePerKg: 4.8,
    availableKg: 500,
    grade: FishGrade.B,
    isHalal: true,
    image: "https://images.unsplash.com/photo-1534080506375-15e05553e1f0?auto=format&fit=crop&q=80&w=600",
    rating: 4.6,
    description: "Harvested from clean organic tanks. Fat and highly active. Excellent for traditional smoking (Keli Salai) or frying.",
    dateListed: "2026-06-10",
  },
  {
    id: "m3",
    fishId: "seabass",
    fishName: "Premium Barramundi (Siakap)",
    fishMalayName: "Ikan Siakap Premium",
    farmName: "Samudra Lagoon Farms",
    farmerName: "Mr. Tan Jin Wei",
    location: "Kupang, Kedah",
    pricePerKg: 11.5,
    availableKg: 120,
    grade: FishGrade.A,
    isHalal: true,
    image: "https://images.unsplash.com/photo-1524704659698-92a40eefdaba?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    description: "Premium sea bass grown in salt-water controlled lagoons. Perfect weight of 800g to 1.2kg per fish, perfect for restaurants.",
    dateListed: "2026-06-12",
  },
  {
    id: "m4",
    fishId: "tilapia",
    fishName: "Red Tilapia Grade B",
    fishMalayName: "Tilapia Merah Gred B",
    farmName: "GlowWater Smallholdings",
    farmerName: "Encik Haziq Salim",
    location: "Ipoh, Perak",
    pricePerKg: 5.8,
    availableKg: 180,
    grade: FishGrade.B,
    isHalal: true,
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=600",
    rating: 4.4,
    description: "Slightly smaller size (400g-600g per fish), perfect for daily household meals or warung use. Very active and healthy.",
    dateListed: "2026-06-09",
  }
];

export const MOCK_BUYERS: BuyerProfile[] = [
  {
    id: "b1",
    name: "Restoran Selera Pantai Timur",
    tag: "Restaurant",
    location: "Kuala Terengganu, Terengganu",
    demandDescription: "Needs persistent supply of Tilapia Merah for signature 'Ikan Bakar' dishes.",
    weeklyDemandKg: 150,
    preferredFish: ["Red Tilapia", "Sea Bass"],
    rating: 4.9,
    contactNumber: "+60 19-983 2345",
  },
  {
    id: "b2",
    name: "Pasar Seni Wet Market Wholesaler",
    tag: "Wholesaler",
    location: "Alor Setar, Kedah",
    demandDescription: "Large distributor buying all grades of Ikan Keli (Catfish) in bulk daily.",
    weeklyDemandKg: 1000,
    preferredFish: ["African Catfish"],
    rating: 4.7,
    contactNumber: "+60 12-441 8765",
  },
  {
    id: "b3",
    name: "FreshMarine Catering Services",
    tag: "Retail Buyer",
    location: "Kota Bharu, Kelantan",
    demandDescription: "Provides wedding and event catering. Prefers high grade seabass and red snapper.",
    weeklyDemandKg: 80,
    preferredFish: ["Barramundi / Sea Bass", "Red Snapper"],
    rating: 4.8,
    contactNumber: "+60 13-912 3009",
  },
  {
    id: "b4",
    name: "Kak Limah Seafood & Tom Yum",
    tag: "Restaurant",
    location: "Gombak, Selangor",
    demandDescription: "Local dinner stall requiring fresh Tilapia and Seabass. Offers top payout on spot delivery.",
    weeklyDemandKg: 60,
    preferredFish: ["Red Tilapia", "Barramundi / Sea Bass"],
    rating: 4.5,
    contactNumber: "+60 17-210 5410",
  }
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "n1",
    type: "earnings",
    titleEn: "Payout Disbursed Successfully",
    titleMs: "Pembayaran Berjaya Dikreditkan",
    bodyEn: "RM450.00 for your sales order with 'Restoran Selera Pantai' has been deposited.",
    bodyMs: "RM450.00 bagi jualan dengan 'Restoran Selera Pantai' telah didepositkan.",
    time: "2 hours ago",
    isRead: false,
  },
  {
    id: "n2",
    type: "orders",
    titleEn: "New Buyer Inquiry!",
    titleMs: "Pertanyaan Pembeli Baru!",
    bodyEn: "Restoran Selera Pantai Timur is asking about your Grade A Tilapia availability.",
    bodyMs: "Restoran Selera Pantai Timur ingin bertanya tentang stok Tilapia Merah Gred A anda.",
    time: "4 hours ago",
    isRead: false,
  },
  {
    id: "n3",
    type: "marketplace",
    titleEn: "Market Price Update",
    titleMs: "Kemas Kini Harga Pasaran",
    bodyEn: "Ikan Siakap (Sea Bass) market price rose by +RM1.50/kg in Terengganu zone today.",
    bodyMs: "Harga pasaran Ikan Siakap meningkat sebanyak +RM1.50/kg di zon Terengganu hari ini.",
    time: "1 day ago",
    isRead: true,
  },
  {
    id: "n4",
    type: "tips",
    titleEn: "Water pH Management Tip",
    titleMs: "Tips Pengurusan pH Air",
    bodyEn: "Ensure water pH is between 6.5 - 8.0 after heavy rain to prevent Tilapia fish stress.",
    bodyMs: "Pastikan pH air antara 6.5 - 8.0 selepas hujan lebat untuk mengelakkan stress ikan Tilapia.",
    time: "2 days ago",
    isRead: true,
  }
];

export const INITIAL_USER_LISTINGS: UserListing[] = [
  {
    id: "ul1",
    fishName: "Red Tilapia (Tilapia Merah)",
    weightKg: 80,
    pricePerKg: 6.5,
    status: "active",
    datePosted: "2026-06-11",
    location: "Kuala Terengganu",
    description: "Grown in high aeration biofloc tanks. Average weight 600g per fish. Feed with premium protein meal pellets.",
    buyerInquiries: 3,
  },
  {
    id: "ul2",
    fishName: "Fresh African Catfish (Ikan Keli)",
    weightKg: 150,
    pricePerKg: 5.0,
    status: "sold",
    datePosted: "2026-05-28",
    location: "Kuala Terengganu",
    description: "Fully matured kelis, harvested last week. All inquiries resolved.",
    buyerInquiries: 5,
  }
];

export const INITIAL_PROFIT_RECORDS: ProfitRecord[] = [
  {
    id: "p1",
    date: "2026-06-11",
    fishName: "Red Tilapia (Tilapia Merah)",
    weightKg: 120,
    purchaseCost: 350.00, // feed, fingerlings, etc.
    sellingPrice: 6.50,
    revenue: 780.00,
    profit: 430.00,
    roi: 122.8,
  },
  {
    id: "p2",
    date: "2026-06-03",
    fishName: "African Catfish (Ikan Keli)",
    weightKg: 200,
    purchaseCost: 400.00,
    sellingPrice: 5.00,
    revenue: 1000.00,
    profit: 600.00,
    roi: 150.0,
  },
  {
    id: "p3",
    date: "2026-05-18",
    fishName: "Red Tilapia (Tilapia Merah)",
    weightKg: 90,
    purchaseCost: 300.00,
    sellingPrice: 6.50,
    revenue: 585.00,
    profit: 285.00,
    roi: 95.0,
  }
];

export const DECAL_GUIDE_STEPS: FarmGuideStep[] = [
  {
    id: "g1",
    titleEn: "1. Pond/Tank Setup",
    titleMs: "1. Penyediaan Kolam/Tangki",
    descriptionEn: "Use durable HDPE canvas or biofloc tanks. Ensure robust aeration with an air pump. Clean water of chlorine before introducing fingerlings.",
    descriptionMs: "Gunakan tangki kanvas HDPE atau sistem bioflok. Pastikan pengudaraan (aerator) yang kuat. Nyah-klorin air sebelum melepaskan anak ikan.",
    icon: "Layers",
  },
  {
    id: "g2",
    titleEn: "2. Seed Selection & Stocking",
    titleMs: "2. Pemilihan Baka & Pelepasan",
    descriptionEn: "Buy certified healthy fingerlings (2-3 inches). Acclimatize the plastic bag in the water for 15 minutes before slowly releasing them into the tank.",
    descriptionMs: "Beli anak ikan sihat yang diperakui (2-3 inci). Apungkan beg anak ikan di kolam selama 15 minit bagi menyamakan suhu air sebelum dilepaskan.",
    icon: "Waves",
  },
  {
    id: "g3",
    titleEn: "3. Feeding & Water Regulation",
    titleMs: "3. Pemberian Makanan & Kawalan Air",
    descriptionEn: "Feed 2-3 times daily matching 3% of total body weight. Test pH (target 6.5-8) and ammonia levels weekly. Add probiotics to sustain dense biofloc community.",
    descriptionMs: "Beri makan 2-3 kali sehari, kadar 3% berat ikan. Uji nilai pH (sasaran 6.5-8) dan ammonia setiap minggu. Tambah probiotik bioflok untuk air optimum.",
    icon: "Sparkles",
  },
  {
    id: "g4",
    titleEn: "4. Fast Harvesting & Sale",
    titleMs: "4. Penuaian & Pemasaran Segar",
    descriptionEn: "Tilapia is ready to harvest in 5-6 months when weight reaches 500g+. List your stock on AquaHub to access local B2B restaurant buyers in one click.",
    descriptionMs: "Ikan Tilapia sedia dituai dalam 5-6 bulan apabila capai 500g+. Letakkan listing di AquaHub untuk dihubungkan terus ke pembeli borong & restoran.",
    icon: "TrendingUp",
  }
];

export const TRANSLATIONS = {
  en: {
    appName: "AquaHub",
    tagline: "Grow Fish. Grow Income.",
    welcomeBack: "Welcome back,",
    todayEarnings: "Today's Earnings",
    farmDashboard: "Fish Price Dashboard",
    farmPrice: "Farm Price",
    marketPrice: "Market Price",
    potentialProfit: "Potential profit by direct trading",
    quickActions: "Quick Actions",
    buyFish: "Buy Fish",
    findBuyers: "Find Buyers",
    profitTracker: "Profit Tracker",
    farmingGuide: "Farming Guide",
    availableFish: "Fish Stock Trade Prices",
    availableQty: "Available Quantity",
    certifiedHalal: "Halal Certified",
    qualityChecked: "Quality Checked",
    qualityGrade: "Grade",
    buyNow: "Order Now",
    sellNow: "Sell Harvest",
    profitCalc: "Profit & ROI Calculator",
    home: "Home",
    marketplace: "Market",
    sellTab: "Sell Fish",
    trackerTab: "Tracker",
    profile: "Profile",
    b40IncentiveTitle: "Financial Opportunity Alert",
    b40IncentiveDesc: "Earn RM500–RM1,000/month through home back-yard fish farming.",
    startFarming: "Begin Farming",
    learnMore: "Learn Aquaculture",
    currency: "RM",
    kg: "kg",
    searchPlaceholder: "Search fresh fish listings...",
    allTypes: "All Types",
    allLocations: "All Locations",
    filterTitle: "Filters",
    gradeLabel: "Grade Selection",
    halfDiscountBanner: "Buy 10kg or more and earn 10% discount!",
    createListing: "Create New Fish Listing",
    previewListing: "Preview Listing",
    uploadPrompt: "Upload Fresh Harvest Photos",
    fishType: "Fish Type",
    weightAvailable: "Available Weight (kg)",
    pricePerKg: "Price per kg (RM)",
    location: "Location",
    description: "Listing Description (Feed details, freshness)",
    submitListing: "Post Listing to Marketplace",
    sellerDashboard: "Your Seller Dashboard",
    activeListings: "Active Harvests",
    soldListings: "Successfully Sold",
    totalSales: "Total Sales Volume",
    buyerInquiries: "Buyer Inquiries",
    buyerDiscovery: "Buyer Discovery Network",
    buyerDiscoveryDesc: "Connect directly with verified local restaurants and Wholesalers buying fresh catches.",
    weeklyDemand: "Weekly Catch Demand",
    preferredSpecies: "Needs:",
    contactBuyer: "WhatsApp / Call Buyer",
    profitSummary: "Farming Performance Summary",
    totalRevenue: "Total Revenue",
    totalProfit: "Total Profit",
    monthlyIncome: "Monthly Income",
    fishSold: "Total Fish Sold",
    recordNewSale: "Log Harvest Sale Record",
    purchaseCost: "Farming Cost (Feed/Fry/Pond setup)",
    sellingPriceLabel: "Selling Price per kg",
    calculate: "Calculate Estimates",
    estRevenue: "Estimated Revenue",
    estProfit: "Estimated Profit",
    estRoi: "Return on Investment (ROI)",
    motivationalPrompt: "You are on track to exceed RM850 in profit this month!",
    qualityHalalStatus: "Trust & Quality Certifications",
    govermentApproved: "JAKIM Halal & Freshness Guaranteed",
    profileTitle: "Farmer Profile",
    farmInfo: "Farm Details",
    membershipLevel: "Farmer Level",
    totalRevenueEarned: "Cumulative Earnings",
    settings: "Settings",
    languageLabel: "App Language (Bahasa Melayu / English)",
    myOrders: "My Orders",
    myListings: "My Active Tank Stock",
    myFarm: "My Smart Biofloc Setup",
    support: "Help & Support",
    logout: "Log Out",
    notifTitle: "Notifications & Price Alerts",
    noInquiries: "No buyer inquiries yet.",
    saveDraft: "Save Draft",
    successPost: "Listing posted successfully! It is now live on the marketplace.",
    successLog: "Sale logged into Profit Tracker successfully!",
    allNotif: "All Alerts",
    buyerInquiryAction: "Inquiry",
  },
  ms: {
    appName: "AquaHub",
    tagline: "Ternak Ikan. Tambah Pendapatan.",
    welcomeBack: "Selamat kembali,",
    todayEarnings: "Pendapatan Hari Ini",
    farmDashboard: "Dashboard Harga Pasaran Ikan",
    farmPrice: "Harga Kolam (Borong)",
    marketPrice: "Harga Pasaran (Runcit)",
    potentialProfit: "Potensi untung dengan jualan terus",
    quickActions: "Pilihan Pantas",
    buyFish: "Beli Ikan",
    findBuyers: "Cari Pembeli",
    profitTracker: "Penjejak Untung",
    farmingGuide: "Panduan Ternakan",
    availableFish: "Harga Pasaran Stok Ikan",
    availableQty: "Kuantiti Tersedia",
    certifiedHalal: "Disahkan Halal",
    qualityChecked: "Kualiti Dijamin",
    qualityGrade: "Gred",
    buyNow: "Pesan Sekarang",
    sellNow: "Jual Hasil",
    profitCalc: "Kalkulator Keuntungan & ROI",
    home: "Utama",
    marketplace: "Pasar",
    sellTab: "Jual Ikan",
    trackerTab: "Penjejak",
    profile: "Profil",
    b40IncentiveTitle: "Peluang Jana Pendapatan B40",
    b40IncentiveDesc: "Jana RM500–RM1,000 sebulan melalui ternakan ikan kontena/bioflok di rumah.",
    startFarming: "Mula Ternakan",
    learnMore: "Belajar Akuakultur",
    currency: "RM",
    kg: "kg",
    searchPlaceholder: "Cari hasil tangkapan segar...",
    allTypes: "Semua Ikan",
    allLocations: "Semua Lokasi",
    filterTitle: "Penapis",
    gradeLabel: "Pilihan Gred",
    halfDiscountBanner: "Beli 10kg ke atas untuk diskaun 10% rakan niaga!",
    createListing: "Iklankan Hasil Tangkapan Baru",
    previewListing: "Pratonton Iklan",
    uploadPrompt: "Muat Naik Gambar Tangkapan Segar",
    fishType: "Jenis Ikan",
    weightAvailable: "Berat Tersedia (kg)",
    pricePerKg: "Harga Per kg (RM)",
    location: "Lokasi Kolam",
    description: "Keterangan Iklan (Jenis makanan, tarikh tuai)",
    submitListing: "Siarkan Iklan ke Pasaran",
    sellerDashboard: "Dashboard Jualan Anda",
    activeListings: "Iklan Aktif",
    soldListings: "Berjaya Dijual",
    totalSales: "Jumlah Jualan Keseluruhan",
    buyerInquiries: "Mesej Pembeli",
    buyerDiscovery: "Rangkaian Pembeli Sah",
    buyerDiscoveryDesc: "Hubungi terus restoran, kantin, dan pemborong tempatan yang memerlukan bekalan harian.",
    weeklyDemand: "Permintaan Mingguan",
    preferredSpecies: "Keperluan Ikan:",
    contactBuyer: "WhatsApp / Hubungi Pembeli",
    profitSummary: "Ringkasan Prestasi Ternakan",
    totalRevenue: "Jumlah Jualan",
    totalProfit: "Jumlah Untung Bersih",
    monthlyIncome: "Pendapatan Bulan Ini",
    fishSold: "Kuantiti Terjual",
    recordNewSale: "Log Rekod Jualan Hasil",
    purchaseCost: "Kos Ternakan (Makanan/Benih/Kolam)",
    sellingPriceLabel: "Harga Jualan per kg",
    calculate: "Kira Anggaran Untung",
    estRevenue: "Anggaran Hasil Jualan",
    estProfit: "Anggaran Untung Bersih",
    estRoi: "Pulangan Pelaburan (ROI)",
    motivationalPrompt: "Anda berada di landasan betul untuk jana RM850 untung bulan ini!",
    qualityHalalStatus: "Sijil Kepercayaan & Halal",
    govermentApproved: "Disahkan Halal oleh JAKIM & Segar Gred A",
    profileTitle: "Profil Penternak",
    farmInfo: "Maklumat Kolam",
    membershipLevel: "Tahap Penternak",
    totalRevenueEarned: "Jumlah Pendapatan Terkumpul",
    settings: "Tetapan",
    languageLabel: "Bahasa Aplikasi (Bahasa Melayu / English)",
    myOrders: "Pesanan Saya",
    myListings: "Stok Kolam Aktif Saya",
    myFarm: "Sistem Bioflok Pintar Saya",
    support: "Bantuan & Hubungi Kami",
    logout: "Log Keluar",
    notifTitle: "Notifikasi & Amaran Harga",
    noInquiries: "Tiada mesej daripada pembeli lagi.",
    saveDraft: "Simpan Draf",
    successPost: "Iklan berjaya disiarkan! Stok anda kini boleh dilihat di Marketplace.",
    successLog: "Rekod jualan berjaya disimpan ke Penjejak Untung!",
    allNotif: "Semua Amaran",
    buyerInquiryAction: "Mesej",
  }
};
